# Generated by Django 4.0.4 on 2022-04-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
    ]
